FROM tibiscuit14/reprohackaton2025:nf-r-deseq

# Dependencies install
RUN R -e "install.packages('graph', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('RBGL', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('KEGGgraph', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('SPIA', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/openssl/openssl_0.9.6.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R6/R6_2.2.2.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/httpuv/httpuv_1.3.5.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/sourcetools/sourcetools_0.1.5.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/hwriter/hwriter_1.3.2.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/shiny/shiny_1.0.3.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/httr/httr_1.2.1.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('AnnotationHub', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('ensembldb', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('ShortRead', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R.methodsS3/R.methodsS3_1.7.1.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R.oo/R.oo_1.21.0.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R.utils/R.utils_2.5.0.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/aroma.light/aroma.light_3.6.0.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('EDASeq', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('biovizBase', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('GO.db', repos='https://bioconductor.org/packages/3.5/data/annotation', type='source')"
RUN R -e "install.packages('PFAM.db', repos='https://bioconductor.org/packages/3.5/data/annotation', type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/SparseM/SparseM_1.77.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('topGO', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('GSEABase', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('GOstats', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('Rgraphviz', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/progress/progress_1.1.2.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/reshape/reshape_0.8.6.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/GGally/GGally_1.3.2.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('ggbio', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('ReportingTools', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/png/png_0.1-7.tar.gz', repos=NULL, type='source')"

RUN R -e "install.packages('KEGGREST', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"
RUN R -e "install.packages('org.Hs.eg.db', repos='https://bioconductor.org/packages/3.5/data/annotation', type='source')"
RUN R -e "install.packages('pathview', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/shape/shape_1.4.2.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('GlobalOptions', repos='https://cran.r-project.org', type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/circlize/circlize_0.4.1.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/rjson/rjson_0.2.15.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('GetoptLong', repos='https://cran.r-project.org', type='source')"
RUN R -e "install.packages('dendextend', repos='https://cran.r-project.org', type='source')"
RUN R -e "install.packages('ComplexHeatmap', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"

RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R.methodsS3/R.methodsS3_1.7.1.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R.oo/R.oo_1.21.0.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/R.utils/R.utils_2.5.0.tar.gz', repos=NULL, type='source')"

# EnrichmentBrowser install
RUN R -e "install.packages('EnrichmentBrowser', repos='https://bioconductor.org/packages/3.5/bioc', type='source')"