FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    unzip \
    wget \
    gffread\
    && rm -rf /var/lib/apt/lists/*

# Download NCBI Datasets CLI
RUN wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets \
    && chmod +x datasets \
    && mv datasets /usr/local/bin/ \
    && wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat \
    && chmod +x dataformat \
    && mv dataformat /usr/local/bin/

WORKDIR /data
CMD ["datasets", "help"]
