FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Bowtie 0.12.7 install
RUN apt-get update && apt-get install -y wget xz-utils && \
    wget https://sourceforge.net/projects/bowtie-bio/files/bowtie/0.12.7/bowtie-0.12.7-linux-x86_64.zip && \
    apt-get install -y unzip && \
    unzip bowtie-0.12.7-linux-x86_64.zip -d /opt && \
    rm bowtie-0.12.7-linux-x86_64.zip

ENV PATH="/opt/bowtie-0.12.7:${PATH}"

CMD ["bowtie"]
