FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Python2 install
RUN apt-get update && apt-get install -y \
    python2 \
    python2-dev \
    wget \
    build-essential \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# pip install
RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py && \
    python2 get-pip.py && \
    rm get-pip.py

# cutadapt 1.11 install
RUN pip2 install cutadapt==1.11

CMD ["cutadapt"]

